FROM public.ecr.aws/lambda/python:3.9

ENV PIP_ROOT_USER_ACTION=ignore

COPY action_requirements.txt  .
RUN pip3 install -r action_requirements.txt
RUN yum install -y git

COPY engineer engineer
COPY action action

ENTRYPOINT ["python", "-m", "action"]